// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFYEUVGWILB-dnh1HXJKYhaPaXsI5i-8',
    appId: '1:104318694544:web:02eb7b91b0930d4c271415',
    messagingSenderId: '104318694544',
    projectId: 'tripxtravelagencyuserapp',
    authDomain: 'tripxtravelagencyuserapp.firebaseapp.com',
    storageBucket: 'tripxtravelagencyuserapp.appspot.com',
    measurementId: 'G-L38WZ36L1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0LyymwIRIm7wCCkd_tjeQkKF7wnGxa0',
    appId: '1:104318694544:android:f351b5599fc2b6ee271415',
    messagingSenderId: '104318694544',
    projectId: 'tripxtravelagencyuserapp',
    storageBucket: 'tripxtravelagencyuserapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHC1l795x-S3OeLxZWpnSOk6iMnW5DKu4',
    appId: '1:104318694544:ios:95249d50e221de86271415',
    messagingSenderId: '104318694544',
    projectId: 'tripxtravelagencyuserapp',
    storageBucket: 'tripxtravelagencyuserapp.appspot.com',
    iosBundleId: 'com.example.tripxUserApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHC1l795x-S3OeLxZWpnSOk6iMnW5DKu4',
    appId: '1:104318694544:ios:95249d50e221de86271415',
    messagingSenderId: '104318694544',
    projectId: 'tripxtravelagencyuserapp',
    storageBucket: 'tripxtravelagencyuserapp.appspot.com',
    iosBundleId: 'com.example.tripxUserApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdFYEUVGWILB-dnh1HXJKYhaPaXsI5i-8',
    appId: '1:104318694544:web:fe111db08970b623271415',
    messagingSenderId: '104318694544',
    projectId: 'tripxtravelagencyuserapp',
    authDomain: 'tripxtravelagencyuserapp.firebaseapp.com',
    storageBucket: 'tripxtravelagencyuserapp.appspot.com',
    measurementId: 'G-Q0V25604NH',
  );
}
